---
title: "CI"
output: html_document
date: '2023-11-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)


```

## Load the data
```{r}

data <- read.csv("measurements_03_47.csv")

head(data)

```

## Calculate 95% CI

```{r}

# to calculate 95% confidence intervals, need mean and std

data1 <- data %>% 
  group_by(Type, Size) %>% 
  summarize(
    mean = mean(Time),
    n = length(Time),
    std = sd(Time),
    se = std / sqrt(n)
    
  )

data1

```

```{r}
# CI is +- 2* std


data_CI <-  data1 %>% 
  mutate(
    CI_upper = mean + 2*std,
    CI_lower = mean - 2*std)

data_CI


```


## Plot 

```{r}

data_CI$Type = as.factor(data_CI$Type)

data_CI %>% 
  ggplot(aes(Size, mean, color=Type)) + 
  geom_point() +
  geom_errorbar(aes(ymin=CI_upper, ymax=CI_lower)) +
  geom_line() +
  scale_y_log10()   # to see better since it's small

```


## Linear regression


```{r}

data_CI %>% 
 ggplot(aes(Size, mean, color=Type)) + 
  geom_point() +
  geom_smooth(method='lm')

```


### Type only
```{r}

model <- lm(mean ~ Type, data = data_CI)
summary(model)

```

```{r}

contrasts(data_CI$Type)

```
Intercept = built-in  \
Type Parallel = built-in - parallel  \
Type Sequential = built-in - sequential  \



```{r}

# data_CI %>% 
#   group_by(Type) %>% 
#   summarise(
#     mean_T = mean(mean)
#   )

```



### Size only

```{r}

model <- lm(mean ~ Size, data = data_CI)
summary(model)

```



### Both
```{r}

model <- lm(mean ~ Type * Size, data = data_CI)
summary(model)

```
Contrasts?




### Both (sum coding)

```{r}

contrasts(data_CI$Type) = contr.sum(3)

model <- lm(mean ~ Type * Size, data = data_CI)
summary(model)


#data_CI$Type
```
Intercept = mean - built-in?  \
Type1 = mean -   paral?  \
Type2 = mean - seq  \


why 2 interactions?  \


```{r}

# data_CI$Type
# 
# grandmean <- mean(data_CI$mean)
# 
# data_builtin<- subset(data_CI, Type == " Built-in")
# 
# builtin <- mean(data_builtin$mean)
# 
# grandmean - builtin


```


## Separate Size and type - separate regression model for each type of algorithm

```{r}

data_builtin<- subset(data_CI, Type == " Built-in")

model <- lm(mean ~ Size, data = data_builtin)
summary(model)

```


```{r}


data_seq<- subset(data_CI, Type == " Sequential")

model <- lm(mean ~ Size, data = data_seq)
summary(model)

```

```{r}


data_parallel<- subset(data_CI, Type == " Parallel")

model <- lm(mean ~ Size, data = data_parallel)
summary(model)

```


```{r}

```

```{r}

```




```{r}


```

```{r}

```